import { interactionIcons, socialIcons } from "./icons";

export const mockSocialData = [
  {
    thumbnailSrc: "https://i.ibb.co/fVRCnNZY/school2.webp",
    avatarSrc: "https://i.ibb.co/sdn1mj9s/AVATAR-midtone-ux-instrgram.jpg",
    platformIcon: socialIcons.twitter,
    authorName: "Sarah Anderson",
    username: "@sarahand",
    content:
      "Excited to announce our school's new STEM program launching next month! Students will have access to cutting-edge labs and mentorship from industry professionals. #Education #STEM #Innovation",
    platform: "Twitter",
    date: "Aug 20, 2021 • 6:25 AM",
    likes: 247,
    comments: 42,
    shares: 189,
    likeIcon: interactionIcons.heart,
    commentIcon: interactionIcons.comment,
    shareIcon: interactionIcons.retweet,
  },
  {
    thumbnailSrc: "https://i.ibb.co/dJDHGnDz/student1.webp",
    avatarSrc: "https://i.ibb.co/v4GRFBbB/AVATAR-Kostis-Kapelonis.png",
    platformIcon: socialIcons.instagram,
    authorName: "Michael Chen",
    username: "@mikec_design",
    content:
      "Proud of our students who participated in the regional science fair! Their innovative projects on renewable energy solutions impressed everyone. Congrats to all participants! #ScienceFair #StudentSuccess",
    platform: "Instagram",
    date: "Sep 12, 2021 • 2:45 PM",
    likes: 584,
    comments: 32,
    shares: 76,
    likeIcon: interactionIcons.heart,
    commentIcon: interactionIcons.comment,
    shareIcon: interactionIcons.upload,
  },
  {
    thumbnailSrc: "https://i.ibb.co/J8QjpbD/school1.webp",
    avatarSrc: "https://i.ibb.co/W4YnsHJX/AVATAR-couponcodefinder.jpg",
    platformIcon: socialIcons.facebook,
    authorName: "Emily Rodriguez",
    username: "@emilyteaches",
    content:
      "Open house this Saturday! Join us from 10am-2pm to tour our campus, meet faculty, and learn about our academic programs. Refreshments will be provided. We can't wait to see you there! #OpenHouse #CampusTour",
    platform: "Facebook",
    date: "Oct 5, 2021 • 11:30 AM",
    likes: 312,
    comments: 47,
    shares: 129,
    likeIcon: interactionIcons.thumb,
    commentIcon: interactionIcons.comment,
    shareIcon: interactionIcons.share,
  },
];
