import { CartItem } from './types';

export const labelStyles: Record<string, string> = {
  researcher: 'text-[#1D77BD] bg-[#dbe9fe]',
  monitor: 'text-[#991b1b] bg-[#fee2e1]',
  report: 'text-[#db7303] bg-[#fff3c6]',
  profile: 'text-[#0B6333] bg-[#E5FEF0]',
  addon: 'text-[#464646] bg-[#e4e4e4]',
  analytics: 'text-[#6366f1] bg-[#e0e7ff]',
  monitoring: 'text-[#7c2d12] bg-[#fed7aa]',
  boost: 'text-[#be185d] bg-[#fce7f3]',
};

export const initialCartItems: CartItem[] = [
  {
    id: 1,
    title: 'Researcher Plan',
    description: 'Power user features with ad-free experience, advanced comparisons, and data export capabilities',
    image: 'https://i.ibb.co/5NTkykV/product3.jpg',
    price: 19.00,
    period: '/ month',
    label: { text: 'Individual Plan', color: 'researcher' },
    stats: [
      { icon: 'ad-free', value: 'Ad-Free' },
      { icon: 'compare', value: 'Compare 10' },
      { icon: 'export', value: 'Export CSV' },
    ],
    features: ['Custom Collections', 'Historical Data', 'Premium Support'],
  },
  {
    id: 2,
    title: 'Monitor Packs',
    description: 'Real-time alerts for specific listing changes with daily monitoring frequency',
    image: 'https://i.ibb.co/XkdtT1Y/product2.png',
    price: 350,
    period: '/ year',
    originalPrice: 420,
    label: { text: 'Monitoring', color: 'monitor' },
    stats: [
      { icon: 'bell', value: '5 Monitors' },
      { icon: 'clock', value: 'Daily Checks' },
    ],
    specifics: [
      { label: 'Billing', value: 'Annual (2 months free)' },
      { label: 'Alerts', value: 'Email + On-site' },
      { label: 'Fields', value: 'Price, Status, Contact Info' },
    ],
  },
  {
    id: 3,
    title: 'Report Packs',
    description: 'Unlock detailed contact information and premium reports with credits that never expire',
    image: 'https://i.ibb.co/BHcDXgQ/product5.webp',
    price: 159,
    period: '/ month',
    originalPrice: 199,
    label: { text: 'Reports', color: 'report' },
    stats: [
      { icon: 'lock', value: '25 Reports' },
      { icon: 'calendar', value: 'Monthly' },
    ],
    specifics: [
      { label: 'Type', value: 'Subscription (20% savings)' },
      { label: 'Reports/Month', value: '25 credits' },
      { label: 'Includes', value: 'Contact details, ownership info' },
    ],
  },
  {
    id: 4,
    title: 'Enhanced Profile Management',
    description: 'Complete brand control with verified status, premium features, and full profile editing capabilities',
    image: 'https://i.ibb.co/5NTkykV/product3.jpg',
    price: 480,
    period: 'total (6 months)',
    originalPrice: 600,
    label: { text: 'Enhanced', color: 'profile' },
    stats: [
      { icon: 'eye', value: '2,000 Views/mo' },
      { icon: 'calendar', value: '6 Months' },
    ],
    specifics: [
      { label: 'Rate', value: '$0.05 per view' },
      { label: 'Discount', value: '20% (6-month plan)' },
      { label: 'Features', value: 'Offers, newsletters, verified badge' },
    ],
  },
  {
    id: 5,
    title: 'Verified Profile Add-on',
    description: 'Build maximum trust with a premium verified badge for your owner profile across all listings',
    image: 'https://i.ibb.co/XkdtT1Y/product2.png',
    price: 99,
    period: '/ year',
    label: { text: 'Add-on', color: 'addon' },
    stats: [
      { icon: 'shield', value: 'Trust Badge' },
      { icon: 'users', value: 'All Profiles' },
    ],
    specifics: [
      { label: 'Coverage', value: 'All owned listings' },
      { label: 'Duration', value: 'Annual subscription' },
      { label: 'Verification', value: 'Business documents required' },
    ],
  },
  {
    id: 6,
    title: 'Team Management Add-on',
    description: 'Allow multiple team members to manage and collaborate on your account listings',
    image: 'https://i.ibb.co/BHcDXgQ/product5.webp',
    price: 700,
    period: '/ year',
    originalPrice: 840,
    label: { text: 'Team', color: 'addon' },
    stats: [
      { icon: 'users', value: '5 Members' },
      { icon: 'lock', value: 'Role-based Access' },
    ],
    specifics: [
      { label: 'Members', value: '5 team members' },
      { label: 'Billing', value: 'Annual (2 months free)' },
      { label: 'Permissions', value: 'Custom role management' },
    ],
  },
  {
    id: 7,
    title: 'Enhanced Listing Analytics',
    description: 'Get detailed insights and performance metrics for your listings with advanced analytics dashboard',
    image: 'https://i.ibb.co/5NTkykV/product3.jpg',
    price: 249,
    period: '/ year',
    label: { text: 'Analytics', color: 'analytics' },
    stats: [
      { icon: 'chart', value: '3 Listings' },
      { icon: 'zap', value: 'Real-time' },
    ],
    specifics: [
      { label: 'Coverage', value: '3 premium listings' },
      { label: 'Metrics', value: 'Views, clicks, conversions' },
      { label: 'Reports', value: 'Weekly & monthly summaries' },
    ],
  },
  {
    id: 8,
    title: 'Internal Competitor Monitoring',
    description: 'Monitor competitors within the platform and track key metrics and changes in real-time',
    image: 'https://i.ibb.co/XkdtT1Y/product2.png',
    price: 229,
    period: '/ year',
    label: { text: 'Internal Monitor', color: 'monitoring' },
    stats: [
      { icon: 'eye', value: '5 Competitors' },
      { icon: 'clock', value: 'Daily Updates' },
    ],
    specifics: [
      { label: 'Scope', value: 'Platform listings only' },
      { label: 'Tracking', value: 'Pricing, reviews, offerings' },
      { label: 'Alerts', value: 'Price changes, new reviews' },
    ],
  },
  {
    id: 9,
    title: 'External Competitor Monitoring',
    description: 'Advanced monitoring including external data sources with comprehensive competitor analysis',
    image: 'https://i.ibb.co/BHcDXgQ/product5.webp',
    price: 449,
    period: '/ year',
    label: { text: 'External Monitor', color: 'monitoring' },
    stats: [
      { icon: 'search', value: '5 Competitors' },
      { icon: 'zap', value: 'Multi-platform' },
    ],
    specifics: [
      { label: 'Sources', value: 'External platforms & websites' },
      { label: 'Data', value: 'Social media, web presence, reviews' },
      { label: 'Reports', value: 'Weekly competitive intelligence' },
    ],
  },
  {
    id: 10,
    title: 'Invite to Review Pack',
    description: 'Send review invitations to your customers and build trust with authentic feedback',
    image: 'https://i.ibb.co/5NTkykV/product3.jpg',
    price: 199,
    period: '/ pack',
    label: { text: 'Invites', color: 'addon' },
    stats: [
      { icon: 'mail', value: '25 Invites' },
      { icon: 'shield', value: 'Verified Only' },
    ],
    specifics: [
      { label: 'Delivery', value: 'Email & SMS options' },
      { label: 'Templates', value: 'Customizable messages' },
      { label: 'Tracking', value: 'Response rates & analytics' },
    ],
  },
  {
    id: 11,
    title: 'Boosted Listings Campaign',
    description: 'Promote your listing with priority placement on competitor pages for maximum visibility',
    image: 'https://i.ibb.co/XkdtT1Y/product2.png',
    price: 4500,
    period: 'total campaign',
    originalPrice: 5000,
    label: { text: 'Promotion', color: 'boost' },
    stats: [
      { icon: 'eye', value: '50,000 Impressions' },
      { icon: 'clock', value: '30 Days' },
    ],
    specifics: [
      { label: 'Placement', value: 'Competitor listing pages' },
      { label: 'Rate', value: '$0.10 per impression' },
      { label: 'Discount', value: '10% volume discount applied' },
      { label: 'Analytics', value: 'Real-time performance tracking' },
    ],
  },
];

