export const SIDE_TABS = {
  MONTHLY_UPDATE: "Monthly Update",
  REPORT_CARD: "Report Card",
  ABOUT: "About",
  RANKINGS: "Rankings",
  ADMISSIONS: "Admissions",
  SCATTER_PLOT: "Scatter plot",
  OVERVIEW: "Overview",
  TESTIMONIALS: "Testimonials",
  LINKS: "Links",
  EVENTS: "Events",
  REVIEWS: "Reviews",
  REVIEW_HIGHLIGHTS: "Review highlights",
  SIMILAR: "Similar",
  MAP: "Map",
  CULTURE: "Culture",
  COST: "Cost",
  MAJORS: "Majors",
  STUDENTS: "Students",
  ACADEMICS: "Academics",
  TEACHERS: "Teachers",
  ACTIVITIES: "Activities",
  SPOTLIGHT: "Spotlight",
  CASE_STUDY: "Case study",
  AFTER_COLLEGE: "After College",
  PROGRAMS: "Programs",
  COMPARISON: "Comparison",
};
