export const SIDE_TABS_MOBILE = {
  MONTHLY_UPDATE_MOBILE: "Monthly Update Mobile",
  REPORT_CARD_MOBILE: "Report Card Mobile",
  ABOUT_MOBILE: "About Mobile",
  RANKINGS_MOBILE: "Rankings Mobile",
  ADMISSIONS_MOBILE: "Admissions Mobile",
  SCATTER_PLOT_MOBILE: "Scatter Plot Mobile",
  OVERVIEW_MOBILE: "Overview Mobile",
  TESTIMONIALS_MOBILE: "Testimonials Mobile",
  LINKS_MOBILE: "Links Mobile",
  EVENTS_MOBILE: "Events Mobile",
  REVIEWS_MOBILE: "Reviews Mobile",
  REVIEW_HIGHLIGHTS_MOBILE: "Review Highlights Mobile",
  SIMILAR_MOBILE: "Similar Mobile",
  MAP_MOBILE: "Map Mobile",
  CULTURE_MOBILE: "Culture Mobile",
  COST_MOBILE: "Cost Mobile",
  MAJORS_MOBILE: "Majors Mobile",
  STUDENTS_MOBILE: "Students Mobile",
  ACADEMICS_MOBILE: "Academics Mobile",
  TEACHERS_MOBILE: "Teachers Mobile",
  ACTIVITIES_MOBILE: "Activities Mobile",
  SPOTLIGHT_MOBILE: "Spotlight Mobile",
  CASE_STUDY_MOBILE: "Case Study Mobile",
  AFTER_COLLEGE_MOBILE: "After College Mobile",
  AREA_MOBILE: "Area Mobile",
  PROGRAMS_MOBILE: "Programs Mobile",
  SOCIAL_MEDIA_MOBILE: "Social Media Mobile",
  COMPARISON_MOBILE: "Comparison Mobile",
  ARTICLES_MOBILE: "Articles Mobile",
};

export const SIDE_TABS_DESKTOP = {
  MONTHLY_UPDATE_DESKTOP: "Monthly Update Desktop",
  REPORT_CARD_DESKTOP: "Report Card Desktop",
  ABOUT_DESKTOP: "About Desktop",
  RANKINGS_DESKTOP: "Rankings Desktop",
  ADMISSIONS_DESKTOP: "Admissions Desktop",
  SCATTER_PLOT_DESKTOP: "Scatter Plot Desktop",
  OVERVIEW_DESKTOP: "Overview Desktop",
  TESTIMONIALS_DESKTOP: "Testimonials Desktop",
  LINKS_DESKTOP: "Links Desktop",
  EVENTS_DESKTOP: "Events Desktop",
  REVIEWS_DESKTOP: "Reviews Desktop",
  REVIEW_HIGHLIGHTS_DESKTOP: "Review Highlights Desktop",
  SIMILAR_DESKTOP: "Similar Desktop",
  MAP_DESKTOP: "Map Desktop",
  CULTURE_DESKTOP: "Culture Desktop",
  COST_DESKTOP: "Cost Desktop",
  MAJORS_DESKTOP: "Majors Desktop",
  STUDENTS_DESKTOP: "Students Desktop",
  ACADEMICS_DESKTOP: "Academics Desktop",
  TEACHERS_DESKTOP: "Teachers Desktop",
  ACTIVITIES_DESKTOP: "Activities Desktop",
  SPOTLIGHT_DESKTOP: "Spotlight Desktop",
  CASE_STUDY_DESKTOP: "Case Study Desktop",
  AFTER_COLLEGE_DESKTOP: "After College Desktop",
  AREA_DESKTOP: "Area Desktop",
  PROGRAMS_DESKTOP: "Programs Desktop",
  SOCIAL_MEDIA_DESKTOP: "Social Media Desktop",
  COMPARISON_DESKTOP: "Comparison Desktop",
  ARTICLES_DESKTOP: "Articles Desktop",
};
