import { School } from "./types";

export const schoolsData: School[] = [
  {
    id: 1,
    name: "Harvard University",
    image: "https://i.ibb.co/J8QjpbD/school1.webp",
    rating: 4.9,
    reviewCount: 5347,
    tags: ["Research", "Liberal Arts"],
    moreTags: 2,
    location: "Cambridge, MA",
    duration: "4 yr",
    rank: "A+",
    chances: "89%",
    enrollment: "6,858",
    acceptanceRate: "11%",
    graduationRate: "92%",
    netPrice: "$33,499",
    satRange: "1490-1570",
    actRange: "34-35",
    inStateTuition: "$62,260",
    outOfStateTuition: "$62,260",
    medianEarnings: "$83,600",
    employedRate: "89%",
  },
  {
    id: 2,
    name: "Stanford University",
    image: "https://i.ibb.co/example/stanford.webp",
    rating: 4.8,
    reviewCount: 4123,
    tags: ["Technology", "Innovation"],
    moreTags: 3,
    location: "Stanford, CA",
    duration: "4 yr",
    rank: "A+",
    chances: "85%",
    enrollment: "7,083",
    acceptanceRate: "4%",
    graduationRate: "95%",
    netPrice: "$20,577",
    satRange: "1470-1560",
    actRange: "33-35",
    inStateTuition: "$61,731",
    outOfStateTuition: "$61,731",
    medianEarnings: "$91,200",
    employedRate: "92%",
  },
  {
    id: 3,
    name: "University of California, Berkeley",
    image: "https://i.ibb.co/example/ucberkeley.webp",
    rating: 4.7,
    reviewCount: 6789,
    tags: ["Public Research", "Engineering"],
    moreTags: 1,
    location: "Berkeley, CA",
    duration: "4 yr",
    rank: "A",
    chances: "78%",
    enrollment: "31,814",
    acceptanceRate: "17%",
    graduationRate: "87%",
    netPrice: "$19,329",
    satRange: "1330-1530",
    actRange: "30-34",
    inStateTuition: "$14,226",
    outOfStateTuition: "$43,980",
    medianEarnings: "$74,700",
    employedRate: "85%",
  },
];
